# Generated by Django 4.2.3 on 2024-06-19 12:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0003_certifyinginstitution_certificate"),
    ]

    operations = [
        migrations.RenameField(
            model_name="certificate",
            old_name="certyfiing_institution",
            new_name="certifying_institution",
        ),
    ]
